name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'roo-team-setup/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Display environment info
        run: |
          cd roo-team-setup
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "NPM configuration:"
          npm config list

      - name: Install dependencies
        run: cd roo-team-setup && npm install

      - name: Auto-bump version
        run: |
          cd roo-team-setup
          # Get the current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Split into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          # Increment patch version
          PATCH=$((PATCH + 1))
          # Update version in package.json
          npm version $MAJOR.$MINOR.$PATCH --no-git-tag-version
          echo "New version: $(node -p "require('./package.json').version")"

      - name: Run tests
        run: cd roo-team-setup && npm test || true

      - name: Publish to NPM
        run: cd roo-team-setup && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}