name: Publish to NPM

on:
  push:
    branches:
      - main
    paths:
      - 'roo-team-setup/**'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: cd roo-team-setup && npm install
      - name: Auto-bump version
        run: |
          cd roo-team-setup
          # Get the current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          # Split into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          # Increment patch version
          PATCH=$((PATCH + 1))
          # Update version in package.json
          npm version $MAJOR.$MINOR.$PATCH --no-git-tag-version
      - name: Debug npm configuration
        run: |
          cd roo-team-setup
          echo "Checking npm config..."
          npm config list
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          
      - name: Publish to npm
        run: |
          cd roo-team-setup
          echo "Creating .npmrc with auth token..."
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          echo "Contents of .npmrc (redacted):"
          sed 's/_authToken=.*/_authToken=REDACTED/' .npmrc
          echo "Publishing package..."
          npm publish --verbose --access public
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}